students/net1814080903109/Net1814080903109Activity.java
=> #1 #25 第1次实验

students/net1814080903110/Net1814080903110Activity.java, students/net1814080903110/hzuapps/androidlabs/net1814080903110/Net1814080903110Activity.java
=> #1 #26 第1次实验

students/net1814080903138/Net1814080903138Activity.java
=> #1 #156 第一次实验

students/1814080903103/1814080903103.java, students/net1814080903103/Net1814080903103Activity.java
=> #1 提交实验一代码

students/net1814080903140/Net1814080903140Activity.java
=> #1 #20 第一次实验

students/sec1814080911106/Sec1814080911106Activity.java
=> #1 hzuapps#50 第1次实验

students/net1814080903229/Net1814080903229Activity.java, students/net1814080903229/Net1814080903229MainActivity.java, students/net1814080903229/Net1814080903229TravelActivity.java
=> #1 #126 第1次实验

students/sec1814080911230/AndroidManifest.xml, students/sec1814080911230/app/src/main/AndroidManifest.xml, students/sec1814080911230/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911230/RankActivity.java, students/sec1814080911230/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911230/Sec1814080911230Activity.java, students/sec1814080911230/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911230/StartGameActivity.java, students/sec1814080911230/app/src/main/res/layout/activity_main.xml, students/sec1814080911230/app/src/main/res/layout/activity_rank.xml, students/sec1814080911230/app/src/main/res/layout/activity_start_game.xml, students/sec1814080911230/app/src/main/res/values/colors.xml, students/sec1814080911230/app/src/main/res/values/strings.xml, students/sec1814080911230/app/src/main/res/values/styles.xml, students/sec1814080911230/java/edu/hzuapps/androidlabs/sec1814080911230/RankActivity.java, students/sec1814080911230/java/edu/hzuapps/androidlabs/sec1814080911230/Sec1814080911230Activity.java, students/sec1814080911230/java/edu/hzuapps/androidlabs/sec1814080911230/StartGameActivity.java
=> #2 #43 第二次实验

students/net1814080903229/Net1814080903229LifetipsActivity.java, students/net1814080903229/activity_main.xml
其中的一个Main文件和两个功能文件在我的实验1里   是#582    那三个文件我这里没有显示
=> #2 #126 第2次实验

students/net1814080903137/res/layout/activity_main.xml, students/net1814080903137/res/layout/activity_remind.xml, students/net1814080903137/res/layout/activity_set.xml
=> #4 #165 第四次实验

students/net1814080903116/src/main/activity_treehold.xml
=> #4 #122 第四次实验

students/net1814080903134/app/src/res/layout/activity_main.xml, students/net1814080903134/app/src/res/layout/activity_personal_center.xml, students/net1814080903134/app/src/res/layout/activity_release_idle.xml
=> #4 #140第四次实验

students/net1814080903109/LightenActivity.java
=> #5 #25 第5次实验

students/net1814080903107/LoadDataThread.java, students/net1814080903107/MyLinearLayout.java, students/net1814080903107/MyVariable.java, students/net1814080903107/Net1814080903107Activity.java, students/net1814080903107/StoreActivity.java
=> #5 #27 第5次实验

students/net1814080903316/CourseActivity.java, students/net1814080903316/ImformationActivity.java, students/net1814080903316/Net1814080903316Activity.java, students/net1814080903316/TableActivity.java
=> #6 #54 第六次实验

students/net1814080903320/sqlite/DBOpenHelper.java, students/net1814080903320/sqlite/RunDao.java
=> #5 #62 第5次实验

students/net1814080903226/AndroidManifest.xml, students/net1814080903226/FileDownloadActivity.java, students/net1814080903226/FileDownloader.java, students/net1814080903226/HttpClientActivity.java, students/net1814080903226/activity_file_download.xml, students/net1814080903226/activity_http_client.xml
=> #6 #67 第6次实验

students/net1814080903239/ContentProviderActivity.java, students/net1814080903239/HouseProvider.java, students/net1814080903239/activity_content_provider.xml
=> #5 #86 第5次实验

students/net1814080903213/Database.java, students/net1814080903213/SubmissionFragment.java, students/net1814080903213/SubmitResultActivity.java, students/net1814080903213/Word.java, students/net1814080903213/WordAdapter.java, students/net1814080903213/WordDao.java, students/net1814080903213/WordListFragment.java, students/net1814080903213/activity_submit_result.xml, students/net1814080903213/lab5.md, students/net1814080903213/lab6.md
实验5的本地存储使用 Room 实现，附有第5次实验报告
实验6的 http 请求使用 Volley 实现，附有第6次实验报告
=> #5 #6 #28 第5、6次实验 含实验报告

students/net1814080903136/Music.java, students/net1814080903136/Net1814080903136Activity.java, students/net1814080903136/Utils.java, students/net1814080903136/music.java
暂时只实现了获取本地音乐到列表，由于剪辑等功能没完成剪辑后保存的还没实现
=> #5 #148 第五次实验

students/net1814080903110/AndroidManifest.xml, students/net1814080903110/MainSQLiteOpenHelper.java, students/net1814080903110/Net1814080903110Activity.java, students/net1814080903110/Setting2Activity.java, students/net1814080903110/SettingActivity.java
=> #6 #26 第六次实验

desktop.ini, students/net1814080903111/AndroidManifest.xml, students/net1814080903111/Net1814080903111Activity.java, students/net1814080903111/activity_record.java, students/net1814080903111/activity_record.xml, students/net1814080903111/item_nosign.xml, students/net1814080903111/net_1814080903111_activity.xml, students/net1814080903111/strings.xml
本次实验采用SQLite数据库来保存签到记录，点击签到按钮后，根据今天的日期来保存，同时签到按钮在一天之内禁用。每次使用APP都会先检查今天是否有签到，有则禁用按钮，没有就不禁用，查看签到记录时，也会去查询这个月的签到记录，根据情况显示日期颜色，签到则红色，未签则黑色，不在本月的日期则灰色。
=> #5 #24 第5次实验

students/net1814080903113/DownloadTest.java, students/net1814080903113/download_test.xml
=> #5 #158 第五次实验

students/net1814080903139/src/main/AndroidManifest.xml
=> #6 #420 第六次实验

students/net1814080903124/DonwloadSaveImg.java, students/net1814080903124/FindImage.java
1.创建了DonwloadSaveImg类，**用于保存网络图片（基于图片URL进行下载保存）**。
2.FindImage类中定义用**Json获取图片URL**的方法来获取对应图片的URL（Json文件以及图片存放于申请使用的阿里云ESC服务器中）。
3.显示图片使用第三方库**Glide**来实现。
=> #6 #29 第6次实验

students/net1814080903230/GameActivity.java, students/net1814080903230/MainActivity.java, students/net1814080903230/SetActivity.java, students/net1814080903230/activity_game.xml
未用到网络编程方面的内容，完善自身选题。
在老师指导下参考某英文网站，终于实现获取图片平移时的X坐标进行得分判断，至此选题内容都完成了。
=> #6 #22 第6次实验

students/net1814080903215/UpDownloadActivity.java
无使用网络编程的内容，在界面上添加了调用系统相机拍照并且显示，以及调用系统相册的功能。
=> #6 #12 第6次实验

students/net1814080903137/实验五/CRUD.java, students/net1814080903137/实验五/EditActivity.java, students/net1814080903137/实验五/MainActivity.java, students/net1814080903137/实验五/Note.java, students/net1814080903137/实验五/NoteAdapter.java, students/net1814080903137/实验五/NoteDatabase.java, students/net1814080903137/实验六/AndroidManifest.xml, students/net1814080903137/实验六/FileDownloadActivity.java, students/net1814080903137/实验六/FileDownloader.java, students/net1814080903137/实验六/HttpClientActivity.java, students/net1814080903137/实验六/activity_http_client.xml, students/net1814080903137/实验六/file_layout.xml
=> #5 #165 第5次实验

students/net1814080903103/src/main/java/edu/hzuapps/androidlabs/net1814080903103/ReckonActivity.java, students/net1814080903103/src/main/res/layout/activity_reckon.xml
=> #5 #144 实验5

students/sec1814080911118/app/src/main/java/edu/hzuapps/pyq/LookPyqActivity.java, students/sec1814080911118/app/src/main/java/edu/hzuapps/pyq/Sec1814080911118Activity.java, students/sec1814080911118/app/src/main/java/edu/hzuapps/pyq/SendPyqActivity.java, students/sec1814080911118/app/src/main/java/edu/hzuapps/pyq/listview/Message.java, students/sec1814080911118/app/src/main/java/edu/hzuapps/pyq/listview/MessageAdapter.java, students/sec1814080911118/app/src/main/res/layout/activity_look_pyq.xml, students/sec1814080911118/app/src/main/res/layout/activity_main.xml, students/sec1814080911118/app/src/main/res/layout/activity_send_pyq.xml, students/sec1814080911118/app/src/main/res/layout/message_item.xml, students/sec1814080911118/app/src/main/res/values/colors.xml, students/sec1814080911118/app/src/main/res/values/strings.xml
=> #4 #315 提交实验4

students/net1814080903113/HttpClientUIActivity.java, students/net1814080903113/activity_http_client.xml
=> #6 #158 第六次实验

students/net1814080903103/src/main/java/edu/hzuapps/androidlabs/net1814080903103/AlarmActivity.java, students/net1814080903103/src/main/java/edu/hzuapps/androidlabs/net1814080903103/AlarmReceiver.java, students/net1814080903103/src/main/java/edu/hzuapps/androidlabs/net1814080903103/ClockActivity.java, students/net1814080903103/src/main/res/layout/activity_alarm.xml, students/net1814080903103/src/main/res/layout/activity_alarm2.xml, students/net1814080903103/src/main/res/layout/activity_clock.xml
=> #6 #144 实验6

students/net1814080903116/src/main/PostActivity.java, students/net1814080903116/src/main/TreeholdActivity.java, students/net1814080903116/src/main/activity_main.xml, students/net1814080903116/src/main/activity_post.xml, students/net1814080903116/src/main/activity_treehold.xml, students/net1814080903116/src/main/button_main.xml, students/net1814080903116/src/main/button_treehold.xml
=> #6 #122 第六次实验

students/net1814080903119/MyImageView.java, students/net1814080903119/SaveImageUrl.java, students/net1814080903119/StaticPageActivity.java
实现在ImageView上直接显示网络图片。
图片信息都封装在一个类（SaveImageUrl）里面，方便调用。
=> #6 #31 第6次实验

students/net1814080903209/AccountActivity.java, students/net1814080903209/JsonParse.java, students/net1814080903209/User.java, students/net1814080903209/activity_account.xml, students/net1814080903209/user.json
1. 模拟账号登陆后向后端申请账户信息
2. 首先利用了AsycnhttpClient向本地运行得Tomcat发送了请求，获取user.json中的数据
3. 利用Gson库对json数据进行解析，然后又将获取到的数据进行展示
4. 根据获取到的图像url，用HttpURLConnection向url发送请求
5. 利用Message把图片发给Handler，再显示出来
=> #6 #21 第6次实验

students/sec1814080911111/FileDownload/AndroidManifest.xml, students/sec1814080911111/FileDownload/FileDownloadActivity.java, students/sec1814080911111/FileDownload/FileDownloader.java, students/sec1814080911111/FileDownload/HttpClientActivity.java, students/sec1814080911111/FileDownload/HttpClientUIActivity.java
=> #6 #277 第6次实验

students/net1814080903304/activity_linear_list.xml
=> #6 #52 第六次实验

students/net1814080903318/activity_net1814080903318.xml
=> #6 #101 第六次实验

students/net1814080903325/activity_net1814080903325.xml, students/net1814080903325/activity_player.xml
=> #5 #56 第六次实验

students/net1814080903342/ContentProviderActivity.java, students/net1814080903342/SearchIdActivity.java, students/net1814080903342/SearchTradingActivity.java, students/net1814080903342/TradingProvider.java, students/net1814080903342/activity_content_provider.xml, students/net1814080903342/activity_net1814080903342.xml, students/net1814080903342/activity_search_id.xml, students/net1814080903342/activity_search_trading.xml
=> #5 #259 第5次实验 修改实验4

students/net1814080903337/Net1814080903337/app/src/main/java/edu/hzuapp/androidlabs/net1814080903337/RecordActivity.java
=> #6 #248 第6次实验

students/net1814080903320/activity_friends.xml
我的设计不用用到第七次实验的摄像头等组件编程，所以修改完善的一个界面，以此提交
=> #7 #62 第7次实验

students/sec1814080911111/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911111/CountdownActivity.java, students/sec1814080911111/app/src/main/java/edu/hzuapps/androidlabs/sec1814080911111/TimerActivity.java, students/sec1814080911111/app/src/main/res/layout/activity_countdown.xml, students/sec1814080911111/app/src/main/res/layout/activity_timer.xml
=> #7 #277 第7次实验

students/net1814080903325/AndroidManifest.xml, students/net1814080903325/BasicActivity.java, students/net1814080903325/activity_basic.xml
=> #7 #56 第七次实验

students/net1814080903316/CourseActivity.java, students/net1814080903316/ImformationActivity.java
=> #7 #54 第七次实验 

students/net1814080903334/NetActivity.java, students/net1814080903334/WebTools.java
=> #6 #76 第六次实验
